export const sampleData = [
  {
    Media: "TV",
    Mois: "January",
    DateDebut: "2023-01-05",
    Support: "Canal+",
    heure: "20:30",
    Duree: "30",
    Accroche: "New Year Promotion",
    MarqueProduit: "Faderco Baby",
    ProduitPrincipal: "Diapers",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Baby Care",
    Avant: "News",
    Apres: "Movie",
    Tarif_30s_1pci: "5000",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "January",
    DateDebut: "2023-01-07",
    Support: "Ennahar TV",
    heure: "19:45",
    Duree: "20",
    Accroche: "Winter Special",
    MarqueProduit: "Faderco Cotex",
    ProduitPrincipal: "Feminine Care",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Series",
    Apres: "News",
    Tarif_30s_1pci: "4500",
    TypeAchat: "Sponsorship",
  },
  {
    Media: "TV",
    Mois: "January",
    DateDebut: "2023-01-10",
    Support: "Echorouk TV",
    heure: "21:15",
    Duree: "30",
    Accroche: "Family Care",
    MarqueProduit: "Faderco Familia",
    ProduitPrincipal: "Tissue",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Household",
    Avant: "Movie",
    Apres: "Talk Show",
    Tarif_30s_1pci: "5200",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "January",
    DateDebut: "2023-01-15",
    Support: "Canal+",
    heure: "18:30",
    Duree: "15",
    Accroche: "Quick Clean",
    MarqueProduit: "Faderco Wipes",
    ProduitPrincipal: "Wipes",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Kids Show",
    Apres: "News",
    Tarif_30s_1pci: "3000",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "January",
    DateDebut: "2023-01-20",
    Support: "Ennahar TV",
    heure: "20:00",
    Duree: "30",
    Accroche: "Premium Care",
    MarqueProduit: "Faderco Baby Premium",
    ProduitPrincipal: "Diapers",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Baby Care",
    Avant: "News",
    Apres: "Movie",
    Tarif_30s_1pci: "5500",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "February",
    DateDebut: "2023-02-01",
    Support: "Echorouk TV",
    heure: "19:30",
    Duree: "20",
    Accroche: "February Deals",
    MarqueProduit: "Faderco Cotex Ultra",
    ProduitPrincipal: "Feminine Care",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Series",
    Apres: "Talk Show",
    Tarif_30s_1pci: "4800",
    TypeAchat: "Sponsorship",
  },
  {
    Media: "TV",
    Mois: "February",
    DateDebut: "2023-02-05",
    Support: "Canal+",
    heure: "21:00",
    Duree: "30",
    Accroche: "Family Size",
    MarqueProduit: "Faderco Familia XL",
    ProduitPrincipal: "Tissue",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Household",
    Avant: "Movie",
    Apres: "News",
    Tarif_30s_1pci: "5300",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "February",
    DateDebut: "2023-02-10",
    Support: "Ennahar TV",
    heure: "17:45",
    Duree: "15",
    Accroche: "On-the-Go",
    MarqueProduit: "Faderco Travel Wipes",
    ProduitPrincipal: "Wipes",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Kids Show",
    Apres: "Series",
    Tarif_30s_1pci: "3200",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "February",
    DateDebut: "2023-02-15",
    Support: "Echorouk TV",
    heure: "20:15",
    Duree: "30",
    Accroche: "Night Protection",
    MarqueProduit: "Faderco Baby Night",
    ProduitPrincipal: "Diapers",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Baby Care",
    Avant: "News",
    Apres: "Movie",
    Tarif_30s_1pci: "5600",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "February",
    DateDebut: "2023-02-20",
    Support: "Canal+",
    heure: "19:00",
    Duree: "20",
    Accroche: "Sensitive Care",
    MarqueProduit: "Faderco Cotex Sensitive",
    ProduitPrincipal: "Feminine Care",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Series",
    Apres: "News",
    Tarif_30s_1pci: "4700",
    TypeAchat: "Sponsorship",
  },
  {
    Media: "TV",
    Mois: "March",
    DateDebut: "2023-03-01",
    Support: "Ennahar TV",
    heure: "20:45",
    Duree: "30",
    Accroche: "Spring Fresh",
    MarqueProduit: "Faderco Familia Fresh",
    ProduitPrincipal: "Tissue",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Household",
    Avant: "Movie",
    Apres: "Talk Show",
    Tarif_30s_1pci: "5400",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "March",
    DateDebut: "2023-03-05",
    Support: "Echorouk TV",
    heure: "18:15",
    Duree: "15",
    Accroche: "Antibacterial",
    MarqueProduit: "Faderco Antibac Wipes",
    ProduitPrincipal: "Wipes",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Kids Show",
    Apres: "News",
    Tarif_30s_1pci: "3300",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "March",
    DateDebut: "2023-03-10",
    Support: "Canal+",
    heure: "21:30",
    Duree: "30",
    Accroche: "Extra Absorbent",
    MarqueProduit: "Faderco Baby Extra",
    ProduitPrincipal: "Diapers",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Baby Care",
    Avant: "News",
    Apres: "Movie",
    Tarif_30s_1pci: "5700",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "March",
    DateDebut: "2023-03-15",
    Support: "Ennahar TV",
    heure: "19:15",
    Duree: "20",
    Accroche: "Ultra Thin",
    MarqueProduit: "Faderco Cotex Thin",
    ProduitPrincipal: "Feminine Care",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Series",
    Apres: "Talk Show",
    Tarif_30s_1pci: "4900",
    TypeAchat: "Sponsorship",
  },
  {
    Media: "TV",
    Mois: "March",
    DateDebut: "2023-03-20",
    Support: "Echorouk TV",
    heure: "20:30",
    Duree: "30",
    Accroche: "Kitchen Roll",
    MarqueProduit: "Faderco Familia Kitchen",
    ProduitPrincipal: "Tissue",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Household",
    Avant: "Movie",
    Apres: "News",
    Tarif_30s_1pci: "5500",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "April",
    DateDebut: "2023-04-01",
    Support: "Canal+",
    heure: "17:30",
    Duree: "15",
    Accroche: "Aloe Vera",
    MarqueProduit: "Faderco Aloe Wipes",
    ProduitPrincipal: "Wipes",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Kids Show",
    Apres: "Series",
    Tarif_30s_1pci: "3400",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "April",
    DateDebut: "2023-04-05",
    Support: "Ennahar TV",
    heure: "21:00",
    Duree: "30",
    Accroche: "Active Baby",
    MarqueProduit: "Faderco Baby Active",
    ProduitPrincipal: "Diapers",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Baby Care",
    Avant: "News",
    Apres: "Movie",
    Tarif_30s_1pci: "5800",
    TypeAchat: "Spot",
  },
  {
    Media: "TV",
    Mois: "April",
    DateDebut: "2023-04-10",
    Support: "Echorouk TV",
    heure: "19:45",
    Duree: "20",
    Accroche: "Wings Protection",
    MarqueProduit: "Faderco Cotex Wings",
    ProduitPrincipal: "Feminine Care",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Personal Care",
    Avant: "Series",
    Apres: "News",
    Tarif_30s_1pci: "5000",
    TypeAchat: "Sponsorship",
  },
  {
    Media: "TV",
    Mois: "April",
    DateDebut: "2023-04-15",
    Support: "Canal+",
    heure: "20:15",
    Duree: "30",
    Accroche: "Soft Touch",
    MarqueProduit: "Faderco Familia Soft",
    ProduitPrincipal: "Tissue",
    MarquePrincipale: "Faderco",
    Annonceur: "FADERCO",
    Secteur: "Household",
    Avant: "Movie",
    Apres: "Talk Show",
    Tarif_30s_1pci: "5600",
    TypeAchat: "Spot",
  },
]
